version: '3.8'

networks:
  default:
    name: hawker-finder

volumes:
  data:

services:
  db:
    image: mongo
    container_name: hawker-finder-db
    restart: always
    env_file:
      - ./compose/env
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    # command: 

  ingest:
    container_name: hawker-finder-ingest
    build:
      context: .
      dockerfile: ./compose/ingest/Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - db
    env_file:
      - ./compose/env

  ui:
    container_name: hawker-finder-ui
    build:
      context: .
      dockerfile: ./compose/streamlit/Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - ./compose/env
    depends_on:
      - ingest